### ISSUE TITLE
Cannot connect to Convolution2D layer

### ISSUE THREAD

**Issue by mpariente** [bokorn/Keras-and-Theano-layers-for-Switched-Pooling#2]
Hi bokorn, 

Thanks again for the example you uploaded. 
I wonder if you tried to connect a `Convolution2D` layer on the top of a `max_only_lambda`. 

I tried to implement some kind of a SegNet but it doesn't work yet because I cannot connect the `max_only_lambda` to the next `Convolution2D`.
Here is an example code example of one of the parts that doesn't work : 
```
N=15
U=256
input_shape=(None,1,U,N+1)
index_type='flattened'
index_scope='global'
# Input
inputs = Input(shape=(input_shape[1:]))
# Encoder
# First Tower
c1=Convolution2D(24, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(inputs)
c2=Convolution2D(12, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(c1)

max_switch_1 = MaxPoolSwitch2D((2, 2), strides=(2,2),index_type=index_type,index_scope=index_scope,name="max_switch_1")(c2)
switch_1 = switch_only_lambda(name="switch_1", index_type=index_type)(max_switch_1)
max_1 = max_only_lambda(name="max_1",index_type=index_type)(max_switch_1)

# Second Tower
c3=Convolution2D(32, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(max_1)
c4=Convolution2D(16, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(c3)

model=Model(input=inputs,output=c4)
print('Compile')
model.compile(loss="binary_crossentropy", optimizer='adadelta')

dummy=np.ones((10,1,U,N+1))
preds=model.predict(dummy)
print(preds.shape)
```

And I get this error message : 

```
ValueError                                Traceback (most recent call last)
/home/claire/Bureau/All/Stage2016/To_Cluster/Codes/switch_segnet.py in <module>()
    154 
    155 dummy=np.ones((10,1,U,N+1))
--> 156 preds=model.predict(dummy)
    157 print(preds.shape)
    158 

/home/claire/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc in predict(self, x, batch_size, verbose)
   1217         f = self.predict_function
   1218         return self._predict_loop(f, ins,
-> 1219                                   batch_size=batch_size, verbose=verbose)
   1220 
   1221     def train_on_batch(self, x, y,

/home/claire/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc in _predict_loop(self, f, ins, batch_size, verbose)
    895                 ins_batch = slice_X(ins, batch_ids)
    896 
--> 897             batch_outs = f(ins_batch)
    898             if not isinstance(batch_outs, list):
    899                 batch_outs = [batch_outs]

/home/claire/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.pyc in __call__(self, inputs)
    917     def __call__(self, inputs):
    918         assert isinstance(inputs, (list, tuple))
--> 919         return self.function(*inputs)
    920 
    921 

/home/claire/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    884                     node=self.fn.nodes[self.fn.position_of_error],
    885                     thunk=thunk,
--> 886                     storage_map=getattr(self.fn, 'storage_map', None))
    887             else:
    888                 # old-style linkers raise their own exceptions

/home/claire/anaconda2/lib/python2.7/site-packages/theano/gof/link.pyc in raise_with_op(node, thunk, exc_info, storage_map)
    323         # extra long error message in that case.
    324         pass
--> 325     reraise(exc_type, exc_value, exc_trace)
    326 
    327 

/home/claire/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    871         try:
    872             outputs =\
--> 873                 self.fn() if output_subset is None else\
    874                 self.fn(output_subset=output_subset)
    875         except Exception:

ValueError: CorrMM images and kernel must have the same stack size

Apply node that caused the error: CorrMM{half, (1, 1), (1, 1)}(Subtensor{::, :int64:}.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 50
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(10, 12, 128, 8), (32, 6, 3, 3)]
Inputs strides: [(98304, 4096, 32, 4), (216, 36, -12, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)](TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM{half, (1, 1), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/claire/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/home/claire/anaconda2/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 289, in execfile
    builtin_mod.execfile(filename, *where)
  File "/home/claire/Bureau/All/Stage2016/To_Cluster/Codes/switch_segnet.py", line 133, in <module>
    c3=Convolution2D(32, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(max_1)
  File "/home/claire/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 569, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/claire/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/claire/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 164, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/claire/anaconda2/lib/python2.7/site-packages/keras/layers/convolutional.py", line 442, in call
    filter_shape=self.W_shape)
  File "/home/claire/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1454, in conv2d
    filter_shape=filter_shape)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
I checked : 

- Shape of `max_switch_1=(10,24,128,8)`

-  Shape of `max_1 = (10,12,128,8)`

-  Shape of `switch_1=(10,12,128,8)`

- The CNN works if `c3` receives input from `c2` directly

 
Could you please help me? I would appreciate it a lot! 

Sorry for the long post and huge error message

**Comment by bokorn** [comment]
I'll take a look at it.

**Comment by bokorn** [comment]
Fixed it, there was a change in how sizes where handled in keras and I
needed to update the switched pooling code. Latest push should work.

**Comment by mpariente** [comment]
Thanks a lot ! It works I'm happy :)

Edit : It works for `model.predict` but not for `model.train`... 

```
N=15
U=256
input_shape=(None,1,U,N+1)
index_type='flattened'
index_scope='global'
# Input
inputs = Input(shape=(input_shape[1:]))
# Encoder
# First Tower
c1=Convolution2D(24, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(inputs)
c2=Convolution2D(12, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(c1)

max_switch_1 = MaxPoolSwitch2D((2, 2), strides=(2,2),index_type=index_type,index_scope=index_scope,name="max_switch_1")(c2)
switch_1 = switch_only_lambda(name="switch_1", index_type=index_type)(max_switch_1)
max_1 = max_only_lambda(name="max_1",index_type=index_type)(max_switch_1)

# Second Tower
c3=Convolution2D(32, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(max_1)
c4=Convolution2D(16, 3, 3, border_mode='same',dim_ordering='th',activation='relu')(c3)

model=Model(input=inputs,output=c4)
print('Compile')
model.compile(loss="binary_crossentropy", optimizer='adadelta')

dummy=np.ones((64,1,U,N+1))
dummy_out=np.ones((64,12,128,8))
preds=model.predict(dummy)
print(preds.shape)

nb_epoch = 1
batch_size = 32
print('Train')
history = model.fit(dummy, dummy_out, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1)
```
I get this error message : `TypeError: __init__() got an unexpected keyword argument 'padding'`
(I can post the veryyy looong version of the error message if you want)

Thank you in advance for your help !
